[package]
name = "isolib-rust-sdk"
version = "0.0.1"
edition = "2021"

[lib]
name = "isolib_rust_sdk"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
